### ISSUE TITLE
Error on Mac OS X Sierra

### ISSUE THREAD

**Issue by xheisenbugx** [devos50/vlc-pyqt5-example#1]
I am receiving the next error:

```
Traceback (most recent call last):
  File "/Users/oaaburto/Documents/example.py", line 115, in PlayPause
    self.OpenFile()
  File "/Users/oaaburto/Documents/example.py", line 161, in OpenFile
    self.mediaplayer.set_nsobject(int(self.videoframe.winId()))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

I think that is a problem related to this line:

self.videoframe = QMacCocoaViewContainer(0)

Could you please confirm that?

**Comment by devos50** [comment]
I don't have any error when using the VLC player. What version of (Py)Qt are you using?
